parameters:
  checkpoint_path: "bigscience/bigscience-small-testing"
  data_dir: "flows/musique/data/musique_ans_v1.0_dev.jsonl"
  output_dir: "/mnt/task_wrapper/user_output/artifacts/"
  branch_weighting_fn: None
  max_new_tokens: 100
  superposition_hops: 0
  superposition_prompt_creation_method: "to_prompt_cache"
  generate_temperature: 0.0

# Other options:
# checkpoint_path:
# - 'bigscience/bloomz-1b7'
# - 'bigscience/bloomz-3b'
# - 'bigscience/bloomz-7b1'
# - 'mosaicml/mpt-7b-instruct'